#!/usr/bin/env python3
"""Sync the Netlify `newsletter` form into subscribers.txt.

The announcer routine runs in a sandbox whose egress proxy blocks
api.netlify.com, so it cannot read the list itself. This runs in GitHub
Actions (which has network access) and commits the list into the repo, where
the routine's checkout can read it.

Secrets from the environment:
  NETLIFY_TOKEN  - Netlify personal access token, forms read

Non-secret config:
  NETLIFY_SITE_ID, SUBSCRIBERS_FILE
"""
import os
import re
import sys

import requests

API = "https://api.netlify.com/api/v1"
EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")


def collect_emails(submissions):
    """Pull deduped, sorted subscriber emails out of Netlify submissions.

    Skips honeypot hits (a non-empty bot-field marks spam) and anything that
    doesn't look like an address.
    """
    emails = set()
    for sub in submissions:
        data = sub.get("data") or {}
        if (data.get("bot-field") or "").strip():
            continue
        email = (data.get("email") or "").strip().lower()
        if EMAIL_RE.match(email):
            emails.add(email)
    return sorted(emails)


def fetch_submissions(session, form_id):
    # ponytail: paginate until short page. Netlify caps per_page at 200 and
    # gives no total, so this is the only way to know we reached the end.
    out, page = [], 1
    while True:
        r = session.get(f"{API}/forms/{form_id}/submissions",
                        params={"per_page": 200, "page": page}, timeout=30)
        r.raise_for_status()
        batch = r.json()
        out.extend(batch)
        if len(batch) < 200:
            return out
        page += 1


def main():
    token = os.environ["NETLIFY_TOKEN"]
    site_id = os.environ["NETLIFY_SITE_ID"]
    path = os.environ.get("SUBSCRIBERS_FILE", "subscribers.txt")

    session = requests.Session()
    session.headers["Authorization"] = f"Bearer {token}"

    r = session.get(f"{API}/sites/{site_id}/forms", timeout=30)
    r.raise_for_status()
    forms = [f for f in r.json() if f.get("name") == "newsletter"]
    if not forms:
        # Not "zero subscribers" -- the form is missing, which means form
        # detection is off or the site was never redeployed after enabling it.
        # Failing loudly beats silently writing an empty list.
        sys.exit("No form named 'newsletter' on this site. Check that Netlify "
                 "form detection is enabled and the site has been redeployed.")

    emails = collect_emails(fetch_submissions(session, forms[0]["id"]))

    header = ("# Subscribers to MDSynapse.org new-article notifications.\n"
              "# Generated by scripts/sync_subscribers.py -- do not edit by hand.\n"
              "# Source of truth is the Netlify `newsletter` form.\n")
    with open(path, "w") as fh:
        fh.write(header + "".join(e + "\n" for e in emails))
    print(f"Wrote {len(emails)} subscriber(s) to {path}")


def demo():
    """Self-check for the parsing logic."""
    subs = [
        {"data": {"email": "a@example.com"}},
        {"data": {"email": "A@Example.com"}},           # dedupes case-insensitively
        {"data": {"email": " b@example.com "}},          # whitespace trimmed
        {"data": {"email": "spam@example.com", "bot-field": "x"}},  # honeypot
        {"data": {"email": "not-an-email"}},
        {"data": {"email": ""}},
        {"data": {}},
        {},
    ]
    assert collect_emails(subs) == ["a@example.com", "b@example.com"], collect_emails(subs)
    assert collect_emails([]) == []
    print("ok")


if __name__ == "__main__":
    if "--demo" in sys.argv:
        demo()
    else:
        main()
